### ISSUE TITLE
[FEAT] Game details show wallet network name

### ISSUE THREAD

**Issue by xiaotiandada** [w3itch-crafter/w3itch-frontend#109]
**Is your feature request related to a problem? Please describe.**

- [x]  Game details hold Token Display wallet network name

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xiaotiandada** [comment]
![image](https://user-images.githubusercontent.com/24250627/165527105-d7e6802b-e237-4b3b-ac22-39c03d0ada00.png)

**Comment by w3itch** [comment]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/102356891/165668513-7a6b5860-490d-4508-b121-3a769d2bb621.png">

**Comment by w3itch** [comment]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/102356891/165668562-0f9d2940-995a-4099-81d7-42c27738ba48.png">
