### ISSUE TITLE
[BUG]Genre filter is not implemented

### ISSUE THREAD

**Issue by w3itch** [w3itch-crafter/w3itch-frontend#132]
**Describe the bug**
Games are not filtered by the selected genre
**To Reproduce**
1. Go to ‘https://w3itch.io’
2. Click on 'Genre>Shooter'
3. Nothing happened

**Expected behavior**
Games should be filtered by the selected genre

**Screenshots**
![image](https://user-images.githubusercontent.com/102356891/166928184-04ba524b-da26-4840-8fca-7f2fee8b4a2b.png)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [firefox]
 - Version [99.01]

**Comment by Syntacticlosure** [comment]
fixed in #216
