### ISSUE TITLE
[BUG] "need token to hold" in Andriod APK

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#138]
![U`A%HP8H0 JP6K~27MHJ`GY](https://user-images.githubusercontent.com/2507027/167252671-e442cab8-027c-4724-b484-7b9a33b4ab3c.png)

Hi, some community developer build an Andriod APK of w3itch, but every game is displayed as "need token to hold" and cannot play it.

**Comment by xiaotiandada** [comment]
The default locked state may not be unlocked normally due to some state loss. Need to debug specific reasons

**Comment by xiaotiandada** [comment]
Maybe doesn't have the infura KEY ！
