### ISSUE TITLE
[FEAT] Web3 Game Jam/Hackathon Calendar Bar

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#169]
[Come for the tool, stay for the network](https://cdixon.org/2015/01/31/come-for-the-tool-stay-for-the-network/).
Let's have [a itch style calendar](https://minetest.dustlabs.io/mt/) for Web3 Game Jam and Hackathon event!

![image](https://user-images.githubusercontent.com/2507027/169250391-49ad13bb-3477-4cce-9904-708d3504adfc.png)

Better have a Calendar Feeds first:
https://twitter.com/MinakoOikawa/status/1527040135669223424

**Comment by xiaotiandada** [comment]
FE: https://fullcalendar.io/demos
