### ISSUE TITLE
[FEAT] [New Player] Minetest Support

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#181]
## Background
Similiar to https://github.com/w3itch-crafter/w3itch-frontend/issues/160.  But this time, we'd like to support some completed different player other than EasyRPG. Alternative player types worth considering including [RMMV](https://store.steampowered.com/app/363890/RPG_Maker_MV), [Pico-8](https://www.lexaloffle.com/pico-8.php), [TIC-80](https://tic80.com/), [mkxp-z](https://gitlab.com/mkxp-z/mkxp-z/), etcs.

Some critiria which should be keep in mind when considering their priority:
- Is it an [internet cultural heritage](https://blog.w3itch.io/2022/04/22/W3itch-Weekly-Telegraph-Ep-1/#Why-RM2k2k3) which needs to be preservede urgently?
- Will the integration help a large number of users?
- Does it offer a completely different experience?
- Can it be **run directly in the browser**?
- And of course the most important: is it **open source**?

[Minetest has their own wasm build since early this quarter](https://blog.minetest.net/2022/03/27/March/), it might be a great alternative for our second project type at this moment. So let's focus on minetest first! Utility of minetest world including but not limited to:
- Online office and meetup ([gather.town](https://www.gather.town/))
- New user onboarding and Gamfication for discord channels
- DAO Tools ([daostack](https://daostack.io/), [aragon](https://aragon.org/), etcs)
- Proof of Work for Creator Economy

[Check this SeeDAO channel for further discussion if you are intersted](https://discord.com/channels/841189467128594442/971394034797015080/978578689837109278).

## Implementation
In the end, it might be something like...
![image](https://user-images.githubusercontent.com/2507027/170142095-1977016b-ecb6-4fc7-9964-bc5de5f0445a.png)

A brief roadmap might be:
- [x] Allow user upload a new type of content ---- minetest world. 
https://github.com/w3itch-crafter/w3itch-frontend/pull/189
- [x] Generated a playable server automaticlly. 
Read https://wiki.minetest.net/Setting_up_a_server#Linux
- [x] Allow the user login automatically with their user names (no pwd).
Copy this line https://github.com/w3itch-crafter/w3itch-minetest-frontend/blob/mint/public/minetest/index.html#L198
- [x] Allow user download the current world data in zip.
Same as https://github.com/w3itch-crafter/w3itch-frontend/issues/74, [https://nodecore.mine.nu/world/](https://nodecore.mine.nu/world/)
- [x] Add permission control.
- [x] Discord integration.
Check [fosscord](https://fosscord.com/), or [this mod](https://content.minetest.net/packages/archfan7411/discordmt/ ), or [this](https://content.minetest.net/packages/AliasAlreadyTaken/yl_matterbridge/)?

**Comment by xiaotiandada** [comment]
- [ ] Split game details routing pages and components

**Comment by whyouare111** [comment]
- [ ] Update the `world_name` in `world.mt` to match the zip package name
- [ ] getWorldNameByPort
- [x] getPortByWorldName
- [x] list running servers of minetest worlds
- [x] restart servers of mintest worlds
- [ ]  restart all servers of uploaded worlds when w3itch-backend is restarted
- [ ]  stopping servers after worlds are deleted, reclaiming ports, and port reuse policies
- [ ] permission control of world deletion
- [ ] adjust API to support filtering by kind of project
- [ ] Upper limit control of the number of worlds that can be uploaded.Maybe it is based on server resources and user behavior

**Comment by lychees** [comment]
Well done everyone, I think Minetest Support is kind of stable.
