### ISSUE TITLE
[FEAT] Light/Dark Mode Switch

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#188]
![image](https://user-images.githubusercontent.com/2507027/170134200-2391474c-8dbd-43b9-b571-7695943e7005.png)

Let there be light.

**Comment by xiaotiandada** [comment]
The scope of the task is relatively large, split the task

- [ ] Support theme switching
- [ ] Page
  - [ ] /games
  - [ ] /dashboard
  - [ ] /jams
  - [ ] /game/new
  - [ ] /game/edit/:id
  - [ ] /game/:id
  - [ ] /user (_home)
  - [ ] /user/settings
  - [ ] /user/settings/*
  - [ ] ...

**Comment by xiaotiandada** [comment]
If you don't want to spend too much effort, you can refer to [darkmodejs](https://darkmodejs.learn.uno/)

**Comment by lychees** [comment]
![image](https://user-images.githubusercontent.com/2507027/172076337-cb98a4ae-2073-4648-ba8f-6251c55fa3f5.png)

**Comment by xiaotiandada** [comment]
> ![image](https://user-images.githubusercontent.com/2507027/172076337-cb98a4ae-2073-4648-ba8f-6251c55fa3f5.png)

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/24250627/174341834-e6c86938-5d40-4c55-8854-65c22a55345e.png">
