### ISSUE TITLE
[FEAT] Automatic cover generation

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#199]
- [ ] EasyRPG
- [x] Minetest

This feature should be pretty hard...

**Comment by whyouare111** [comment]
Mintest Mapper: https://wiki.minetest.net/Minetestmapper

**Comment by whyouare111** [comment]
`cover` is optional in `Create new project/Update project ` form after cover could be auto-generated @xiaotiandada

**Comment by lychees** [comment]
We won't do EasyRPG auto cover generation in this release.
