### ISSUE TITLE
[FEAT] auto register when OAuth login failed

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#205]
RT

**Comment by whyouare111** [comment]
Authorize callback when user login in with an GitHub/Discord account which is not bound：
1. Generate an jwt that contains GitHub account information, and append it to the redirect URI.
2. The front-end reprocesses the query param,displays the registration form, then lets user input username.
3. Submit form to an new registration API endpoint without redirecting to GitHub's OAuth2 Page.
