### ISSUE TITLE
[BUG] Minetest crashed in tourist mode.

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#217]
Test link: https://test.w3itch.io/minetest-game/176

Maybe the random username is too long?

![image](https://user-images.githubusercontent.com/2507027/171225892-439bb71d-8692-454d-9142-cc2611202d05.png)

- unlogin, default game        （Crashed while verifacation）
- unlogin, alternative game  （Crashed while verifacation）
- logined, default game        （Accepted）
- logined, alternative game  （Crashed after loading）

**Comment by xiaotiandada** [comment]
If the username is too long, the game should fail to start and close will not show
