### ISSUE TITLE
[FEAT] grant admin privileges for world uploader.

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#220]
https://wiki.minetest.net/Privileges#Server_configuration
According to the above document, there should be a file called "auth.txt" in world.zip. But I cannot find it.

**Comment by whyouare111** [comment]
Now the backend uses sqlite to store auth information by default, so the corresponding file is `auth.sqlite`

**Comment by whyouare111** [comment]
https://github.com/w3itch-crafter/w3itch-backend/pull/39
