### ISSUE TITLE
[FEAT] Display Discord/Github/Ethereum address in profile page if binded.

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#222]
E.g.: https://chiba.test.w3itch.io/zh-CN

Some reference of design:

![image](https://user-images.githubusercontent.com/2507027/171308802-ae8d4c5a-d864-45bd-8803-113d3ade3d0d.png)
https://app.cyberconnect.me/address/cyberlab.eth

![image](https://user-images.githubusercontent.com/2507027/171308858-411cfbd7-3508-4027-8e1b-197deac004a7.png)
https://mirror.xyz/0x6465F1250c9fe162602Db83791Fc3Fb202D70a7B.

![image](https://user-images.githubusercontent.com/2507027/172077570-4ef41654-dce6-4626-9338-5a77d670acad.png).
https://www.lensfrens.xyz/wagmi.lens

The address must have a href to etherscan (when user is in ethereum mainnet). I also require this feature to grab the user's ethereum address to implement in-game token transfer feature. https://github.com/w3itch-crafter/w3itch-frontend/issues/219

**Comment by whyouare111** [comment]
RelMeAuth can be used in Github's social link

**Comment by lychees** [comment]
![image](https://user-images.githubusercontent.com/2507027/172077794-fc7f51aa-0bf1-4ea7-9b28-3da14d955b6d.png)

**Comment by lychees** [comment]
Let's add passport score for each account in profile page.
