### ISSUE TITLE
[BUG] A Minetest game loaded easyRPG player after updated

### ISSUE THREAD

**Issue by whyouare111** [w3itch-crafter/w3itch-frontend#228]
**Describe the bug**

**To Reproduce**
1. Go to https://test.w3itch.io/dashboard
2. Click on 'Edit'
3. Edit ，click on 'UPDATE'，redirect to game page.
4. Click on 'PLAY' ,see error

**Expected behavior**
use Minetest player

**Screenshots**
<img width="855" alt="image" src="https://user-images.githubusercontent.com/72055358/171554905-c9302f56-445f-4417-938a-c163970d4dee.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [firefox]
 - Version [100]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by whyouare111** [comment]
Maybe we can make minetest player under `/game/[id]` and not need another route

**Comment by xiaotiandada** [comment]
```tsx
router.push(`/game/${id}`)
```

Game routing merge

```tsx
/game/:id
/minetest-game/:id
```

```tsx
/game/:id
```

**Comment by CaTcatM200** [comment]
Has been successfully fixed.
Test successful.
Test environment:
OS: Windows10
Browser: Google Chrome v102.0.5005.63
