### ISSUE TITLE
504 bad gateway on w3itch.io[BUG]

### ISSUE THREAD

**Issue by chiba233** [w3itch-crafter/w3itch-frontend#240]
**Describe the bug**

<img width="752" alt="image" src="https://user-images.githubusercontent.com/55350388/172085543-d3f6dcec-def0-4111-9563-fbed2b7b50f5.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Garfield550** [comment]
General server maintenance, now backend service online, close.
