### ISSUE TITLE
[UX] Lost focus in minetest iframe when click fullscreen.

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#245]
![image](https://user-images.githubusercontent.com/2507027/172281095-329cf86a-00fd-4c2e-b763-d62ec45e3608.png)
You need press "TAB" to focus to the iframe, which is quite confused for new users.

![image](https://user-images.githubusercontent.com/2507027/172285091-04011c07-db1f-45b3-b22e-4442097a7415.png)

Another problem is, you can only focus the iframe by click the menu bar, click the game window itself won't help.

**Comment by Syntacticlosure** [comment]
fixed in #247
