### ISSUE TITLE
[UX] Default donation address

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#272]
![image](https://user-images.githubusercontent.com/2507027/173224206-6c8c2004-6802-43a6-a9c1-1114daa26b6b.png)

![image](https://user-images.githubusercontent.com/2507027/173224192-fad332b3-631c-474d-95a6-c30acf7d0423.png)

**Comment by whyouare111** [comment]
``` 
  @ApiProperty({ description: 'Donate wallet address of the creator' })
  @Column({ nullable: true })
  @IsOptional()
  @IsEthereumAddress()
  donationAddress?: string;
```

empty string is not ethereum address
donationAddresss could be set to `null` ins this case

**Comment by lychees** [comment]
Fixed in production.
