### ISSUE TITLE
[FEAT] Replace random username with nanoid 

### ISSUE THREAD

**Issue by xiaotiandada** [w3itch-crafter/w3itch-frontend#282]
**Is your feature request related to a problem? Please describe.**
<img width="729" alt="image" src="https://user-images.githubusercontent.com/24250627/173571033-51cbe8d6-4bd3-4ac7-a2f8-4d566c5761b5.png">

https://github.com/ai/nanoid

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lychees** [comment]
We need to trim this string in order to fix: https://github.com/w3itch-crafter/w3itch-frontend/issues/217.

**Comment by xiaotiandada** [comment]
> 

Replace old rules with new string ID generators

**Comment by xiaotiandada** [comment]
> We need to trim this string in order to fix: #217.

Replace old rules with new string ID generators

**Comment by lychees** [comment]
Never mind what I mentioned above, #217 seems fixed in test net.
