### ISSUE TITLE
[BUG] Most of this webapp & its contents are stolen for that sweet, sweet crypto-cash-grab

### ISSUE THREAD

**Issue by DeadlyBrad42** [w3itch-crafter/w3itch-frontend#341]
**Describe the bug**
The developers seem to have found a site (Itchio), have copy & pasted the idea, stolen the literal code from it, and are trying to get in on this cryptocurrency stuff to make their quick million before the site & "community" implode in on themselves.

**To Reproduce**
1. Go to [Itch.io](https://itch.io/) & support several independent game developers doing what they love (making games & experiments for fun & minimal/no money)
2. Go to [w3itch.io](https://w3itch.io/) & attempt to support independent game developers submitting either half-baked game concepts or (more commonly) finding existing free projects and re-uploading them as their own, in order to make a quick crypto-buck. (This content strategy shared by these "creators" is the same low-effort strategy used to make the w3itchio site itself)
    * Note that _w3itch.io_ couldn't even come up with a unique name, since doing so would mean they had put any amount of effort into this project
4. Verify that this webapp is a complete cash-grab and not worth anyone's time in it's current form

**Expected behavior**
A project idea would warrant enough passion from its developers to stand on its own uniqueness.

**Screenshots**
| w3itch.io | itch.io |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/11592/176541447-51f1256b-ca0f-45f7-8bec-8df11e6962b4.png) | ![image](https://user-images.githubusercontent.com/11592/176541284-eb74c061-8dec-4609-aec9-4bf311d1e2c6.png) |

**Additional context**
FYI you are a not a very good person.

**Comment by BenStigsen** [comment]
I can reproduce this on my Nokia 3310 as well.

**Comment by Garfield550** [comment]
Please follow #340
