### ISSUE TITLE
[BUG] Delete the website and remove yourself from the internet in perpetuity

### ISSUE THREAD

**Issue by DPS2004** [w3itch-crafter/w3itch-frontend#342]
**Describe the bug**
The "bug" is that you are doing this in the first place.

**To Reproduce**
1. Go to your router
2. Unplug it
3. Throw it away
4. Sell all your electronic devices

**Expected behavior**
People like you stop being grifters, and the world is a better place.

**Comment by Garfield550** [comment]
Please follow #340
