### ISSUE TITLE
Remove Copyrighted Content

### ISSUE THREAD

**Issue by miserypancake** [w3itch-crafter/w3itch-frontend#344]
You have stolen the UI of itch.io, blatantly ripping it off, in addition to using their name directly in your project. As far as I'm concerned, this is scam to trick people by using https://github.com/itchio's established brand on an unrelated project for your own profit.

I request that you immediately remove any likeness, including their name, from your project.

Additionally, upon going through the content on your platform, it appears you have stolen many games (see rpgmaker.net) for reupload without the consent of the creators of the games. For the sake of respecting creators and their work, I request that you remove stolen content from your platform.

**Comment by Garfield550** [comment]
Please follow #340
