### ISSUE TITLE
Remove Copyrighted Content [BUG]

### ISSUE THREAD

**Issue by 0v7** [w3itch-crafter/w3itch-frontend#345]
**Describe the bug**
You've stolen the entire frontend of Itch.io, and are using it to shill cryptocurrency and "Web3". 

**To Reproduce**
1. Go to itch.io
2. Go to w3itch.io
3. Compare the two
4. See error of your ways

**Expected behavior**
Not using stolen assets to shill cryptocurrency, a known scam.

**Additional context**
Delete w3itch.io and also throw away your computer.

**Comment by Garfield550** [comment]
Please follow #340
