### ISSUE TITLE
[BUG] You have one of my games from RPG-MAKER on your ripoff site. PLEASE REMOVE IT NOW

### ISSUE THREAD

**Issue by AmonUK** [w3itch-crafter/w3itch-frontend#348]
**Describe the bug**
YOU DO NOT HAVE MY PERMISSION TO HOST MY GAMES ON YOUR SITE. I WILL EMAIL YOU PERSONALLY AND I WANT YOU TO REMOVE THEM NOW.

Also, you are ripping off itch.io's website layout and from what I can see you have other game son there which I know you have no rights to host nor the permission to. Remove these as well as changing the site layout so that you are not ripping off and trying to piggyback off the success of itch.io.

**To Reproduce**
1. Go to 'w3itch.io'
2. Take down my games
3. Change the layout and stop stealing people's work.
4. The error is you as a whole

**Expected behavior**
Don't steal other people's IP and host it without permission. Don't steal other people's CSS and rip off their website layouts and style/colouring.

**Screenshots**
See w3itch.io

Lastly, got back to that very dark, damp corner of the world from whence you came. Don't return. Disconnect your internet connection and get yourself prospectively, a proper life. Idiot!

**Comment by jeremyBanks** [comment]
How about you delete all of the games whose ownership you're not sure of? And the rest of your web site?

**Comment by Garfield550** [comment]
@jeremyBanks We have no legal experience, and as engineers, we can only delete what you think is infringing from the database, and the interface design will write new code to change it.

We also need to follow the directions of the project manager.

**Comment by jeremyBanks** [comment]
What you need to follow is the law. There's no magic words your project manager can share that make it not apply. 

Criminals.

**Comment by quou** [comment]
Law, order and morality don't apply to web 3 tech.

It's because it's *decentralized*!!

**Comment by Garfield550** [comment]
@jeremyBanks Thanks for anything you pointed out, we are collaborating remotely and the project manager will be seeing this issue.

**Comment by DPS2004** [comment]
The *real* way to handle this is simple. Just delete everything that you did not get explicit permission for. People should not have to ask politely that their games not be stolen.

**Comment by lychees** [comment]
Not possible to prove authorship.

**Comment by KenneyNL** [comment]
@lychees See? You just continue, there's not a fiber in your body that might think hey I gotta stop this and make it right with everyone. You just continue, you go on and on and everything you tell to everyone are either lies or isn't sincere. You genuinely hope for this to go over and have a booming business in whatever this thing is supposed to be.

Newsflash; people will hate it, they hate it now and will hate it in the future.

**Comment by lychees** [comment]
> @lychees See? You just continue, there's not a fiber in your body that might think hey I gotta stop this and make it right with everyone. You just continue, you go on and on and everything you tell to everyone are either lies or isn't sincere. You genuinely hope for this to go over and have a booming business in whatever this thing is supposed to be.
> 
> Newsflash; people will hate it, they hate it now and will hate it in the future.

I double checked the submiter's personal website, github repo as well as search on the Internet.
I am still missing the necessary on which games or which archive of the mentioned game...
How can we resolve it?

**Comment by Laim** [comment]
> > @lychees See? You just continue, there's not a fiber in your body that might think hey I gotta stop this and make it right with everyone. You just continue, you go on and on and everything you tell to everyone are either lies or isn't sincere. You genuinely hope for this to go over and have a booming business in whatever this thing is supposed to be.
> > Newsflash; people will hate it, they hate it now and will hate it in the future.
> 
> I double checked the submiter's personal website, github repo as well as search on the Internet. I am still missing the necessary on which games or which archive of the mentioned game... How can we resolve it?

Unless you have explicit permission from the developer of ANY of the games, none of them should be on there.  It's not a Developers job to DMCA you to take down their content, it's your job to get approval to host it in the first place.

**Comment by jeremyBanks** [comment]
> I am still missing the necessary on which games or which archive of the mentioned game...
> How can we resolve it?

You are not qualified to operate a games store if you can't answer basic questions about intellectual property. You are going to keep breaking the law and getting yourself in more trouble. 

Your project is done. Delete it all, before you get sued or charged.
