### ISSUE TITLE
[BUG]Failed to upload game

### ISSUE THREAD

**Issue by w3itch** [w3itch-crafter/w3itch-frontend#39]
**Describe the bug**

Unable to complete upload, error confirmed in developer console

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Create new project'
3. Fill out the form，upload game
4. Unable to complete upload, error confirmed in developer console

**Expected behavior**
The game should be uploaded successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/102356891/163112366-146c933d-c772-4813-bd0f-ea3f3e335640.png)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version []

**Additional context**

It took a long time to fill out the form, and without knowing the reason for the failure, the whole experience was painful.

**Comment by xiaotiandada** [comment]
Because this bug does not display the correct error prompt, we will support a more friendly uploading experience in the future.

#49
