### ISSUE TITLE
[FEAT]Games can be priced at creation time

### ISSUE THREAD

**Issue by w3itch** [w3itch-crafter/w3itch-frontend#43]
**Is your feature request related to a problem? Please describe.**
It's good for players to be able to play games for free, but creators lack channels to be rewarded.

**Describe the solution you'd like**
The game supports accepting donations, or holding certain social tokens to play.The amount is set at creation time.

**Describe alternatives you've considered**
If we have the specified NFT, we can play the game. NFT can be exchanged, like a game cassette.

**Additional context**
[A Note on decimals](https://docs.openzeppelin.com/contracts/3.x/erc20#a-note-on-decimals)

**Comment by xiaotiandada** [comment]
#49
