### ISSUE TITLE
[FEAT]Game projects can be edited / deleted

### ISSUE THREAD

**Issue by w3itch** [w3itch-crafter/w3itch-frontend#45]
**Is your feature request related to a problem? Please describe.**
I created a game and found that some information was wrongly filled in and I wanted to change/remove it, but I found that there is no edit function.

**Describe the solution you'd like**
We can select the game project we have created in the dashboard to edit and update the form.No need to upload the game again if the game file is up to date. If we do want to update the game file, delete the current one and upload a new one.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by xiaotiandada** [comment]
game file

It seems that you don't need to delete the game files, just update it directly

**Comment by xiaotiandada** [comment]
#68
