### ISSUE TITLE
[BUG]Uploading error when drag zip files.

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#53]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2507027/163420731-c4d6d7c9-ea90-4419-83dd-9728fc73ad4a.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/2507027/163420828-c0880fa4-ed5d-4751-a99e-bfc76468ec70.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by w3itch** [comment]
Only MIME Type `application/zip` is supported now.
``` ts
    if (file?.mimetype !== 'application/zip') {
      throw new BadRequestException(`Invalid mimetype: ${file?.mimetype}`);
    }
```
We will check that if MIME Type`applicaiton/x-zip-compressed` is acceptable.
https://mimetype.io/application/x-zip-compressed

**Comment by lychees** [comment]
It works.

**Comment by lychees** [comment]
![image](https://user-images.githubusercontent.com/2507027/164450184-c9e452e2-4ec6-454a-9e10-13783f92066a.png)

It works, but not works in all cases.
Error when drag in reload.
