### ISSUE TITLE
[BUG]Gencache encoding error.

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#55]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2507027/163529842-6497ff8d-a16d-4156-bcb1-ba7d6f860890.png)

Lots of game has resource not found error,
I reload a index.json in my local server, it is fine.
![image](https://user-images.githubusercontent.com/2507027/163529884-dcf3d9d3-a97a-4878-8626-8e8c60e95f01.png)

So the problem maybe related with gencache.

**Additional context**
A simple patch to fix this issue is skip the `index.json`generation step when `index.json` already exists in the uploaded files.

**Comment by lychees** [comment]
I think it might be a upstream bug. Trace [here](https://github.com/EasyRPG/Tools/issues/67).

**Comment by w3itch** [comment]
https://github.com/w3itch-crafter/w3itch-backend/issues/6
