### ISSUE TITLE
[BUG] Cover images were overwritten when I uploaded a new game

### ISSUE THREAD

**Issue by w3itch** [w3itch-crafter/w3itch-frontend#61]
**Describe the bug**
The cover images of games I uploaded before was overwritten and became the same as the cover image of the newly uploaded game.

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Create new project'
3. Upload cover image,save or exit 
4. Go to 'Browse Game'
5. See error (Even if the game is not successfully uploaded)

**Expected behavior**
The cover images of games I uploaded before should not be overwritten.

**Screenshots**
![image](https://user-images.githubusercontent.com/102356891/163679167-77e3d62b-a7a0-486e-8706-893c4444bf5f.png)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]

**Additional context**

**Comment by w3itch** [comment]
The URL of the cover image is `https://storageapi.fleek.co/7f744516-e377-496b-9ab1-4429f50e6a43-bucket/w3itch-test/attachment/10/header.jpg`
All  cover images's file name are `header.jpg`,  the file with this name on fleek is overwritten when a new one is uploaded.
We can change the file name to be unique before uploading, such as adding a timestamp or uuid.

**Comment by lychees** [comment]
![image](https://user-images.githubusercontent.com/2507027/163693029-e85bf5d0-31f7-4f6c-8d33-0f05f2413d39.png)

![image](https://user-images.githubusercontent.com/2507027/163693031-4234ad2e-eacb-4d64-b519-f8ec957530bd.png)

Might relate to this issue.

**Comment by xiaotiandada** [comment]
#68
