### ISSUE TITLE
[FEAT] Switch the network automatically when wallet is connected on an unsupported chain

### ISSUE THREAD

**Issue by w3itch** [w3itch-crafter/w3itch-frontend#67]
**Is your feature request related to a problem? Please describe.**
When I connect my wallet  on an unsupported chain,
<img width="537" alt="image" src="https://user-images.githubusercontent.com/102356891/163762581-0c255741-5c00-4852-b11d-c66f59f940a1.png">
Then I need to manually switch the chain my wallet is on

**Describe the solution you'd like**
 The experience would be smoother if the wallet could be automatically triggered to switch chains，like some DeFi DAPPs

**Comment by lychees** [comment]
The main targets of this project is creators who are using web3 technology for their very first time,
I think require a specific chain id in their registration stage might be a bad idea,
The user needs extra effort to figure out what a chain id is, and possibly google for how to add new networks to metamask.
It also undermines our principle of maintaining **chain neutrality**.

We should postpone this thing until a payment actually happens.

**Comment by w3itch** [comment]
Now it supports registering on the main ethereum network, so users don't need to know how to switch networks at first.
Switching will happen when leading to uniswap/pancakeswap to exchange the required token.
