### ISSUE TITLE
[FEAT]Better mobile experience

### ISSUE THREAD

**Issue by lychees** [w3itch-crafter/w3itch-frontend#86]
Currently, the mobile experience is really bad.

- [x] self-adaption (Game details)
- [x] full-screen button is not work in mobile
- [x] instance view for twitter && telegram (similar to https://github.com/Meta-Network/meta-cms-frontend/issues/144)

[ynoproject](https://ynoproject.net/) has a beautiful UI design, it works well on both PC and mobile environment.
[itch](https://itch.io/games/made-with-easyrpg) doesn't have its own native easyRPG support, but people can still upload their game as an HTML5 app. So they may not behave consistently. I suggest referring to [this game](https://guilvector.itch.io/lcddem).

![image](https://user-images.githubusercontent.com/2507027/164331468-8620a25b-2b00-4e35-bf8c-75167cf3b9b9.png)

![image](https://user-images.githubusercontent.com/2507027/164331501-3e39864b-df98-4d60-ba04-31db3d00e3af.png)

**Comment by xiaotiandada** [comment]
![image](https://user-images.githubusercontent.com/24250627/164463187-4f16c26c-4df4-434f-a847-ce576f188068.png)
![image](https://user-images.githubusercontent.com/24250627/164463251-4bd682b0-5e1e-4ce6-a822-d1f1d6292ec6.png)

**Comment by xiaotiandada** [comment]
![image](https://user-images.githubusercontent.com/24250627/164463398-cca3e483-eba3-464d-a531-23f23f08f256.png)
![image](https://user-images.githubusercontent.com/24250627/164463475-f2868152-c139-48ec-bb2a-a44a87d22af3.png)

**Comment by xiaotiandada** [comment]
![image](https://user-images.githubusercontent.com/24250627/164463600-11bbea8e-d3c3-46ff-9e32-fdd467ef0d0a.png)

**Comment by xiaotiandada** [comment]
![image](https://user-images.githubusercontent.com/24250627/164596862-33a4e9b8-e2c1-4412-a569-2a76c6a4e0a5.png)

**Comment by w3itch** [comment]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/102356891/164598505-2a364e0b-63c0-4473-8df8-52b39b65e107.png">

**Comment by xiaotiandada** [comment]
IOS

WeChat
![1bdcc45ae4320e0583c2b0a2af068c9](https://user-images.githubusercontent.com/24250627/164705093-fa791193-2bfe-4d7d-b3f1-a8ac04c9e8df.jpg)
![4f7547a9760b53e4f979c99a1d8114b](https://user-images.githubusercontent.com/24250627/164705321-3aa6f975-efd7-4d45-ba3e-c901a443a236.jpg)



Chrome
![57729435344760785f4fdbe03497ccf](https://user-images.githubusercontent.com/24250627/164705125-47370fc9-7440-44c1-a0c8-8e76985aa8a1.jpg)
![79b8b2b9cd2bf565af511e8ba8ff225](https://user-images.githubusercontent.com/24250627/164705139-1c3c15df-8d97-4587-a114-5cd84fea7ff0.jpg)

safari
![7a1f4cbdd4cc1308a1f4936a206b53e](https://user-images.githubusercontent.com/24250627/164705205-5926f495-947f-4adf-a701-5d9c4ba778e6.jpg)
![cd507bc4a746f8e445d545134c55395](https://user-images.githubusercontent.com/24250627/164705222-c4025be6-2a80-479e-8874-2b7369d419a2.jpg)
![60fc06cfa670f15cfb1d307d2767929](https://user-images.githubusercontent.com/24250627/164705256-4b8307d5-78e8-4b9c-bc27-c4f36ab66243.jpg)

safari pwa
![13936b6650f030a876423717bdb8820](https://user-images.githubusercontent.com/24250627/164705310-091522dc-041e-43de-a393-0e65bc8ca8ec.jpg)
![ef86798323757fc9bc02c53becf56cd](https://user-images.githubusercontent.com/24250627/164705332-7beaac53-9a13-4b70-b070-4dfdcfa82499.jpg)

**Comment by xiaotiandada** [comment]
- [ ] Personal homepage card style fix

**Comment by w3itch** [comment]
<img width="817" alt="image" src="https://user-images.githubusercontent.com/102356891/165054646-e3320a6a-1d0b-46ad-860b-5c05590ad984.png">
ipad

**Comment by xiaotiandada** [comment]
- [ ] optimize ipad display
