### ISSUE TITLE
[BUG]The error message persists after updated the file name 

### ISSUE THREAD

**Issue by w3itch** [w3itch-crafter/w3itch-frontend#99]
**Describe the bug**
I tried to upload this game:https://www.rmarchiv.de/games/630, which file name is `Alter A.I.L.A. Genesis - [Vollversion-VV]-2010-11-24`.
<img width="386" alt="image" src="https://user-images.githubusercontent.com/102356891/165047342-42d4aa41-825c-4d46-8ab2-556cadd9d85d.png">
Then update the file name to `Alter A.I.L.A. Genesis.zip` (shorter than 50 characters), the message still existed.
Clicked "Save", the file can be uploaded successfully.

**To Reproduce**
1. Go to 'Dashbaord'
2. Click on 'Create new project'
3. Scroll down to 'Drag & drop some files here, or click to select files'
4. Upload file, As I described in the previous section
5. See Error

**Expected behavior**
Validate the form after reselecting the file and refreshing the validation results.

**Screenshots**
<img width="617" alt="image" src="https://user-images.githubusercontent.com/102356891/165048985-4fdb979a-bad1-4852-b7c1-a43bdb02db51.png">
<img width="493" alt="image" src="https://user-images.githubusercontent.com/102356891/165049017-ebfa9cf9-bbc4-4add-9ac6-0609a2c2e2e1.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [firefox]
 - Version [99.01]

**Comment by lychees** [comment]
https://github.com/w3itch-crafter/w3itch-frontend/issues/90 
Let's solve this one together!
